version: '3.7'

services:
  app:
    container_name: logru-app
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:prod
    env_file:
      - .env
    depends_on:
      - mongo
  mongo:
    container_name: logru-mongo
    image: mongo
    ports:
      - '0.0.0.0:${MONGO_PORT}:27017'
    volumes:
      - mongo-data:/data
networks:
  back:
volumes:
  app:
  mongo-data:
